repos:
  - repo: local
    hooks:
      - id: hpack
        name: hpack
        entry: hpack
        language: system
        files: ^(package\.yaml|cert-prep\.cabal)$
        pass_filenames: false
      - id: fourmolu
        name: fourmolu
        entry: fourmolu --quiet --mode inplace
        language: system
        files: \.hs$
      - id: hlint
        name: hlint
        entry: hlint
        language: system
        files: \.hs$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--strict, -c, .yamllint]
