{ pkgs, config, ... }:
{
  packages = [
    pkgs.hlint
    pkgs.hpack
  ];
  languages.haskell = {
    enable = true;
    # Enable this as soon as lsp supports 9.14.1
    # package = pkgs.haskell.compiler.ghc9141;
    cabal.enable = true;
    lsp.enable = true;
    stack.enable = false;
  };

  # Replaces .pre-commit-config.yaml with an autogenerated symlink.
  git-hooks.hooks = {
    hpack = {
      enable = true;
      entry = "hpack";
      files = "^(package\\.yaml|cert-prep\\.cabal)$";
      pass_filenames = false;
    };
    local-fourmolu = {
      enable = true;
      name = "fourmolu";
      entry = "fourmolu";
      files = ".*\\.hs$";
      args = [
        "--mode"
        "inplace"
      ];
    };
    hlint.enable = true;
    yamllint = {
      enable = true;
      args = [
        "--strict"
        "-c"
        ".yamllint"
      ];
    };
  };

  tasks = {
    "cert-prep:build".exec = "cabal build --project-file=cabal.fast.project";
    "cert-prep:test" = {
      exec = "cabal test --project-file=cabal.fast.project --test-show-details=always";
      after = [ "cert-prep:build" ];
      before = [ "devenv:enterTest" ];
    };
    "cert-prep:lint".exec = "hlint src app test";
  };

  env = {
    GEMINI_API_KEY = config.secretspec.secrets.GEMINI_API_KEY;
    GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai";
    GEMINI_MODEL = "gemini-3.7-flash";
  };
}
