name: cert-prep
version: 0.1.0.0
license: MIT
license-file: LICENSE
author: Paul Grillenberger
maintainer: grillenbergerpaul@gmail.com

language: GHC2021
default-extensions:
  - OverloadedStrings

dependencies:
  - base < 5
  - text
  - containers

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
    - -threaded
  dependencies:
    - aeson
    - microlens-th
    - random

executables:
  cert-prep:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cert-prep
      - aeson
      - brick
      - bytestring
      - microlens
      - microlens-mtl
      - random
      - vty
      - vty-crossplatform

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - aeson
      - cert-prep
      - hspec
