name: cert-prep
version: 0.1.0.0
license: MIT
license-file: LICENSE
author: Paul Grillenberger
maintainer: grillenbergerpaul@gmail.com

language: GHC2021
default-extensions:
  - OverloadedStrings

dependencies:
  - base < 5
  - text
  - containers

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
  dependencies:
    - aeson
    - bytestring
    - directory
    - filepath
    - random
    - time

internal-libraries:
  cert-prep-tui:
    source-dirs: app
    ghc-options:
      - -Wall
      - -O2
    dependencies:
      - cert-prep
      - brick
      - microlens
      - microlens-mtl
      - microlens-th
      - optparse-applicative
      - time
      - vector
      - vty
      - vty-crossplatform

executables:
  cert-prep:
    main: Main.hs
    source-dirs: exe
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cert-prep
      - cert-prep-tui
      - aeson
      - brick
      - bytestring
      - random
      - vty
      - vty-crossplatform

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
    build-tools:
      - hspec-discover
    dependencies:
      - cert-prep
      - cert-prep-tui
      - aeson
      - bytestring
      - directory
      - hspec
      - QuickCheck
      - random
      - temporary
      - time
      - microlens
      - vector
